### ISSUE TITLE
KungFu implementation TODO

### ISSUE THREAD

**Issue by luomai** [lsds/KungFu#29]
- [ ] Enable the order group (by passing reducible tensor's names into the kungfu-world through TF operator attributes). 
  - [x] use attr for passing name: #30
  - [ ] choose the correct VariableMgr, @luomai currently the variableMgr doesn't perform all_reduce for all grads, which cause our order group never completes.
- [ ] Support multiple machines 
- [ ] Huawei Cloud + TF benchmark
